// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHaJm2UZzVKA5U9avIbSXcSlx4CGeKf1g',
    appId: '1:234556147137:web:3af181d1262fe4e8ab1b40',
    messagingSenderId: '234556147137',
    projectId: 'coffeeapp-5d7fc',
    authDomain: 'coffeeapp-5d7fc.firebaseapp.com',
    storageBucket: 'coffeeapp-5d7fc.appspot.com',
    measurementId: 'G-NJ7MT4RWLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlF_SY-Y6ht1hnI9Ac1J5vUlAOKYU8M8',
    appId: '1:234556147137:android:074bbc6b8eee9f1dab1b40',
    messagingSenderId: '234556147137',
    projectId: 'coffeeapp-5d7fc',
    storageBucket: 'coffeeapp-5d7fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLX-uLVOgpYPaGu5JQV8loSj84Tsw_og4',
    appId: '1:234556147137:ios:f700b52bcb398361ab1b40',
    messagingSenderId: '234556147137',
    projectId: 'coffeeapp-5d7fc',
    storageBucket: 'coffeeapp-5d7fc.appspot.com',
    iosBundleId: 'com.example.coffeeOrderApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLX-uLVOgpYPaGu5JQV8loSj84Tsw_og4',
    appId: '1:234556147137:ios:f700b52bcb398361ab1b40',
    messagingSenderId: '234556147137',
    projectId: 'coffeeapp-5d7fc',
    storageBucket: 'coffeeapp-5d7fc.appspot.com',
    iosBundleId: 'com.example.coffeeOrderApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHaJm2UZzVKA5U9avIbSXcSlx4CGeKf1g',
    appId: '1:234556147137:web:7c25e2495e57d613ab1b40',
    messagingSenderId: '234556147137',
    projectId: 'coffeeapp-5d7fc',
    authDomain: 'coffeeapp-5d7fc.firebaseapp.com',
    storageBucket: 'coffeeapp-5d7fc.appspot.com',
    measurementId: 'G-QH58Y6EL1Z',
  );

}